# -*- mode: ruby -*-
# # vi: set ft=ruby :

# # Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "centos65-x86_64-20140116"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"

  config.ssh.forward_agent = true

  config.vm.define :node_setagaya12 do |node_setagaya12|
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "tasks/01.bootstrap.yml"
  end

end
